#!/bin/bash
if [ "`echo $HOSTNAME|grep tux$11 -c`" = "1" ]; then
	/etc/init.d/networking restart
	arp -d ipaddress
	ifconfig eth0 down
	ifconfig eth0 up
	ifconfig eth0 172.16.$10.1/24
	route add -net 172.16.$11.0/24 gw 172.16.$10.254
	route add default gw 172.16.$10.254
	echo "search lixa.fe.up.pt\nnameserver 172.16.1.1\n" > /etc/resolv.conf
	ifconfig
fi
if [ "`echo $HOSTNAME|grep tux$14 -c`" = "1" ]; then
	arp -d ipaddress
	ifconfig eth0 down
	ifconfig eth1 down
	ifconfig eth1 up
	ifconfig eth0 up
	ifconfig eth0 172.16.$10.254/24
	ifconfig eth1 172.16.$11.253/24
	route add default gw 172.16.$11.254
	echo 1 > /proc/sys/net/ipv4/ip_forward
	echo 0 > /proc/sys/net/ipv4/icmp_echo_ignore_broadcasts
	echo "search lixa.fe.up.pt\nnameserver 172.16.1.1\n" > /etc/resolv.conf
	ifconfig
fi
if [ "`echo $HOSTNAME|grep tux$12 -c`" = "1" ]; then
	arp -d ipaddress
	ifconfig eth0 down
	ifconfig eth0 up
	ifconfig eth0 172.16.$11.1/24
	route add -net 172.16.$10.0/24 gw 172.16.$11.253
	route add default gw 172.16.$11.254
	echo "search lixa.fe.up.pt\nnameserver 172.16.1.1\n" > /etc/resolv.conf
	ifconfig
fi
route -n
